# Generated by Django 5.2.12 on 2026-03-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('mae', models.FloatField(default=0)),
                ('mse', models.FloatField(default=0)),
                ('rmse', models.FloatField(default=0)),
                ('r2', models.FloatField(default=0)),
                ('is_best', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='FuturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_sales', models.FloatField()),
                ('forecast_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_predictions', to='forecasting.forecastresult')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesDataset',
        ),
    ]
