# Generated by Django 5.2.12 on 2026-03-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_forecastresult_futureprediction_delete_salesdataset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='futureprediction',
            options={'ordering': ['date']},
        ),
    ]
